config/routes.rb
Rails.application.routes.draw do
  match '/login', to: "page#login", via: [:get, :post]
  match '/otp', to: "page#otp", via: [:get, :post]
  match '/add_otp', to: "page#add_otp", via: [:get, :post]
  get '/logout', to: "auth#logout"
  get '/render_qr', to: "auth#qr"
  get "up" => "rails/health#show", as: :rails_health_check
  root "page#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    has_one_time_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :set_current_session

    protected
    def require_auth
        unless current_user
            redirect_to root_path
        end
    end

    def verify_otp_status
        if session[:user_id].present? && !session[:otp_passed] && @user.otp_enabled
            redirect_to otp_path
        end
    end

    private
    def set_current_session
        @user = current_user
    end

    def current_user
        session[:user_id].present? ? User.find_by(id: session[:user_id]) : nil
    end
end

app/controllers/auth_controller.rb
class AuthController < ApplicationController
  before_action :require_auth, only: [:qr]

  def logout
    session[:user_id] = nil
    session[:otp_passed] = false
    redirect_to root_path
  end

  def qr
    require "rqrcode"

    totp = ROTP::TOTP.new(@user.otp_secret_key, issuer: "OTP Test")
    qrcode = RQRCode::QRCode.new(totp.provisioning_uri(@user.email))
    send_data qrcode.as_png(size: 500), type: 'image/png', disposition: 'inline'
  end
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  before_action :require_auth, only: [:add_otp, :otp]
  before_action :verify_otp_status, except: [:otp]

  def index
  end

  def login
    if request.post?
      email = params[:email]
      password = params[:password]
      user = User.find_by(email: email)

      if user && user.authenticate(password)
        session[:user_id] = user.id
        session[:otp_passed] = false
        redirect_to root_path
      else
        flash[:error] = "Invalid email or password"
        redirect_to login_path
      end
    end
  end

  def otp
    if request.post?
      otp_code = params[:otp_code]
      if @user.authenticate_otp(otp_code)
        session[:otp_passed] = true
        redirect_to root_path
      else
        flash[:error] = "Invalid OTP code"
        redirect_to otp_path
      end
    end
  end

  def add_otp
    if request.post?
      otp_code = params[:otp_code]
      if @user.authenticate_otp(otp_code)
        @user.update!(otp_enabled: true)
        redirect_to root_path
      else
        flash[:error] = "Invalid OTP code"
        redirect_to add_otp_path
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/auth_helper.rb
module AuthHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title OtpTest1
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag "application", "data-turbo-track": "reload"
    = javascript_include_tag "application", "data-turbo-track": "reload", defer: true
  %body
    = yield

app/views/page/add_otp.html.haml
.container.text-center.mt-5
  .row
    .col-md-6.offset-md-3
      .card.mt-4
        .card-body
          %h2 Set Up OTP
          %p
            Scan the QR code below with your OTP authenticator app, or manually enter the key:
          .text-center.mt-4
            = image_tag render_qr_path, alt: 'OTP QR Code', class: 'img-fluid'
          %p.mt-3
            OTP Secret Key:
            %strong= @user.otp_secret_key
          %hr
          %p
            Keep your OTP secret key secure. If lost, you may need to reset your OTP settings.
          = form_with(url: add_otp_path, method: 'post', local: true) do |f|
            .form-group
              = f.label :otp_code, class: 'form-label'
              = f.text_field :otp_code, class: 'form-control', required: true, placeholder: 'Enter OTP Code'
            .mt-4
              = f.submit 'Submit OTP', class: 'btn btn-primary btn-block'
          %p
            = link_to 'Back to Home', root_path, class: 'btn btn-primary btn-block mt-3'

app/views/page/index.html.haml
.container.text-center.mt-5
  .row
    .col-md-6.offset-md-3
      %h1.mb-4 Welcome to Your App
      - if @user.nil?
        .alert.alert-info
          %p
            Please
            = link_to 'Log In', login_path
      - else
        .card.mt-4
          .card-body
            %h2
              = "Hello, #{@user.name}!"
            - if !@user.otp_enabled
              %p
                Your account is not yet secured with OTP.
                %br
                = link_to 'Set up OTP', add_otp_path, class: 'btn btn-primary'
            - else
              %p Your account is secured with OTP.
              %br
              %span.badge.badge-success OTP Enabled
              %br
            = link_to 'Log Out', logout_path, class: 'btn btn-danger'

app/views/page/login.html.haml
.container.text-center.mt-5
  .row
    .col-md-6.offset-md-3
      .card.mt-4
        .card-body
          %h2 Login to Your Account
          - if flash[:error].present?
            .alert.alert-danger
              = flash[:error]
          = form_with(url: login_path, method: 'post', local: true) do |f|
            .form-group
              = f.label :email, class: 'form-label'
              = f.email_field :email, class: 'form-control', required: true, placeholder: 'Email'
            .form-group
              = f.label :password, class: 'form-label'
              = f.password_field :password, class: 'form-control', required: true, placeholder: 'Password'
            .mt-4
              = f.submit 'Log In', class: 'btn btn-primary btn-block'

app/views/page/otp.html.haml
.container.text-center.mt-5
  .row
    .col-md-6.offset-md-3
      .card.mt-4
        .card-body
          %h2 Enter Your OTP Code
          - if flash[:error].present?
            .alert.alert-danger
              = flash[:error]
          = form_with(url: otp_path, method: 'post', local: true) do |f|
            .form-group
              = f.label :otp_code, class: 'form-label'
              = f.text_field :otp_code, class: 'form-control', required: true, placeholder: 'Enter OTP Code'
            .mt-4
              = f.submit 'Submit OTP', class: 'btn btn-primary btn-block'